// FICTIONAL DEMO DATA — NOT REAL INVESTIGATION RECORDS

import type { Document, DocumentVersion } from './types'

export const documentRecords: Document[] = [
  {
    id: 'DOC-DEMO-001',
    caseId: 'CASE-DEMO-1042',
    title: 'Demo Case Intake Summary',
    documentType: 'CASE_REPORT',
    status: 'APPROVED',
    uploadedAt: '2026-08-01T09:15:00.000Z',
    updatedAt: '2026-08-11T14:20:00.000Z',
    currentVersion: 3,
    fileName: 'case-intake-summary-v3.pdf',
    fileSize: '1.4 MB',
    mimeType: 'application/pdf',
    description: 'Fictional summary of initial intake details and preliminary review notes.',
  },
  {
    id: 'DOC-DEMO-002',
    caseId: 'CASE-DEMO-1042',
    title: 'Witness Statement A',
    documentType: 'STATEMENT',
    status: 'UNDER_REVIEW',
    uploadedAt: '2026-08-05T11:45:00.000Z',
    updatedAt: '2026-08-12T08:10:00.000Z',
    currentVersion: 2,
    fileName: 'witness-statement-a-v2.docx',
    fileSize: '842 KB',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    description: 'Fictional witness account prepared for internal review and validation.',
  },
  {
    id: 'DOC-DEMO-003',
    caseId: 'CASE-DEMO-1042',
    title: 'Communication Log',
    documentType: 'CORRESPONDENCE',
    status: 'APPROVED',
    uploadedAt: '2026-08-07T16:30:00.000Z',
    updatedAt: '2026-08-07T16:30:00.000Z',
    currentVersion: 1,
    fileName: 'communication-log-v1.txt',
    fileSize: '125 KB',
    mimeType: 'text/plain',
    description: 'Fictional record of internal communication milestones and follow-up actions.',
  },
  {
    id: 'DOC-DEMO-004',
    caseId: 'CASE-DEMO-1042',
    title: 'Site Photo Index',
    documentType: 'PHOTO_LOG',
    status: 'DRAFT',
    uploadedAt: '2026-08-14T10:00:00.000Z',
    updatedAt: '2026-08-16T09:25:00.000Z',
    currentVersion: 1,
    fileName: 'site-photo-index-v1.xlsx',
    fileSize: '560 KB',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    description: 'Fictional catalog of location photographs and associated annotations.',
  },
  {
    id: 'DOC-DEMO-005',
    caseId: 'CASE-DEMO-2068',
    title: 'Evidence Summary Sheet',
    documentType: 'EVIDENCE_SUMMARY',
    status: 'ARCHIVED',
    uploadedAt: '2026-07-20T13:10:00.000Z',
    updatedAt: '2026-08-04T07:40:00.000Z',
    currentVersion: 2,
    fileName: 'evidence-summary-sheet-v2.pdf',
    fileSize: '980 KB',
    mimeType: 'application/pdf',
    description: 'Fictional summary sheet containing an overview of collected evidence and context.',
  },
]

export const documentVersionRecords: DocumentVersion[] = [
  {
    id: 'DOC-V-1001',
    documentId: 'DOC-DEMO-001',
    version: 1,
    createdAt: '2026-07-28T09:00:00.000Z',
    createdBy: 'Demo Investigator B',
    changeSummary: 'Initial intake summary drafted for early review.',
    status: 'SUPERSEDED',
  },
  {
    id: 'DOC-V-1002',
    documentId: 'DOC-DEMO-001',
    version: 2,
    createdAt: '2026-08-03T10:20:00.000Z',
    createdBy: 'Demo Investigator B',
    changeSummary: 'Updated timeline after first validation pass.',
    status: 'SUPERSEDED',
  },
  {
    id: 'DOC-V-1003',
    documentId: 'DOC-DEMO-001',
    version: 3,
    createdAt: '2026-08-11T14:20:00.000Z',
    createdBy: 'Demo Officer A',
    changeSummary: 'Approved summary with final narrative and corrected references.',
    status: 'ACTIVE',
  },
  {
    id: 'DOC-V-2001',
    documentId: 'DOC-DEMO-002',
    version: 1,
    createdAt: '2026-08-05T11:45:00.000Z',
    createdBy: 'Demo Officer A',
    changeSummary: 'Initial witness statement capture created for review.',
    status: 'SUPERSEDED',
  },
  {
    id: 'DOC-V-2002',
    documentId: 'DOC-DEMO-002',
    version: 2,
    createdAt: '2026-08-12T08:10:00.000Z',
    createdBy: 'Demo Investigator B',
    changeSummary: 'Added clarifying notes and corrected sequence of events.',
    status: 'ACTIVE',
  },
  {
    id: 'DOC-V-3001',
    documentId: 'DOC-DEMO-003',
    version: 1,
    createdAt: '2026-08-07T16:30:00.000Z',
    createdBy: 'Demo Officer A',
    changeSummary: 'Logged initial communication milestones.',
    status: 'ACTIVE',
  },
  {
    id: 'DOC-V-4001',
    documentId: 'DOC-DEMO-004',
    version: 1,
    createdAt: '2026-08-14T10:00:00.000Z',
    createdBy: 'Demo Investigator B',
    changeSummary: 'Created draft index for site photograph inventory.',
    status: 'DRAFT',
  },
  {
    id: 'DOC-V-5001',
    documentId: 'DOC-DEMO-005',
    version: 1,
    createdAt: '2026-07-20T13:10:00.000Z',
    createdBy: 'Demo Officer A',
    changeSummary: 'Created summary for archived case evidence review.',
    status: 'SUPERSEDED',
  },
  {
    id: 'DOC-V-5002',
    documentId: 'DOC-DEMO-005',
    version: 2,
    createdAt: '2026-08-04T07:40:00.000Z',
    createdBy: 'Demo Investigator B',
    changeSummary: 'Archived version updated after final review completion.',
    status: 'ACTIVE',
  },
]
