// FICTIONAL DEMO DATA — NOT REAL INVESTIGATION RECORDS

import type { Evidence, EvidenceTransfer } from './types'

export const evidenceRecords: Evidence[] = [
  {
    id: 'EVD-DEMO-001',
    caseId: 'CASE-DEMO-1042',
    title: 'Demo Digital Exhibit A',
    evidenceType: 'DIGITAL_FILE',
    status: 'STORED',
    collectedAt: '2026-08-02T08:45:00.000Z',
    locationLabel: 'Demo Warehouse Storage Room 2',
    description: 'Fictional digital exhibit prepared for documentation and later review.',
    fileName: 'demo-exhibit-a-archive.zip',
    fileSize: '3.2 MB',
    mimeType: 'application/zip',
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'EVD-DEMO-002',
    caseId: 'CASE-DEMO-1042',
    title: 'Demo Photo Set 1',
    evidenceType: 'PHOTOGRAPH',
    status: 'LOGGED',
    collectedAt: '2026-08-03T14:10:00.000Z',
    locationLabel: 'Demo Site North Entrance',
    description: 'Fictional photo series demonstrating site conditions and observed markers.',
    fileName: 'demo-photo-set-1.jpg',
    fileSize: '1.8 MB',
    mimeType: 'image/jpeg',
    verificationStatus: 'PENDING',
  },
  {
    id: 'EVD-DEMO-003',
    caseId: 'CASE-DEMO-1042',
    title: 'Demo Audio Interview Clip',
    evidenceType: 'AUDIO',
    status: 'REVIEWED',
    collectedAt: '2026-08-06T09:35:00.000Z',
    locationLabel: 'Demo Interview Room 4',
    description: 'Fictional interview audio clip intended for quality review and transcription.',
    fileName: 'demo-interview-clip-01.wav',
    fileSize: '12.4 MB',
    mimeType: 'audio/wav',
    verificationStatus: 'VERIFICATION_UNAVAILABLE',
  },
  {
    id: 'EVD-DEMO-004',
    caseId: 'CASE-DEMO-2068',
    title: 'Demo Physical Item 09',
    evidenceType: 'PHYSICAL_ITEM',
    status: 'TRANSFERRED',
    collectedAt: '2026-07-25T10:05:00.000Z',
    locationLabel: 'Demo Evidence Locker B',
    description: 'Fictional physical item tracked for chain-of-custody documentation.',
    fileName: 'demo-physical-item-09.txt',
    fileSize: '88 KB',
    mimeType: 'text/plain',
    verificationStatus: 'NOT_VERIFIED',
  },
  {
    id: 'EVD-DEMO-005',
    caseId: 'CASE-DEMO-2068',
    title: 'Demo Video Capture',
    evidenceType: 'VIDEO',
    status: 'COLLECTED',
    collectedAt: '2026-07-29T18:20:00.000Z',
    locationLabel: 'Demo Observation Post 3',
    description: 'Fictional video capture used for timeline validation and review planning.',
    fileName: 'demo-video-capture-03.mp4',
    fileSize: '25.6 MB',
    mimeType: 'video/mp4',
    verificationStatus: 'PENDING',
  },
  {
    id: 'EVD-DEMO-006',
    caseId: 'CASE-DEMO-3091',
    title: 'Demo Statement Sheet',
    evidenceType: 'DOCUMENT',
    status: 'RESTRICTED',
    collectedAt: '2026-08-11T12:00:00.000Z',
    locationLabel: 'Demo Secure Archive Cabinet',
    description: 'Fictional statement sheet held under controlled review and restricted access.',
    fileName: 'demo-statement-sheet.pdf',
    fileSize: '640 KB',
    mimeType: 'application/pdf',
    verificationStatus: 'VERIFIED',
  },
]

export const evidenceTransferRecords: EvidenceTransfer[] = [
  {
    id: 'XFER-DEMO-001',
    evidenceId: 'EVD-DEMO-001',
    timestamp: '2026-08-02T08:50:00.000Z',
    fromLabel: 'Demo Site Team',
    toLabel: 'Demo Evidence Vault',
    action: 'Collected',
    notes: 'Fictional collection logged for digital evidence intake.',
    status: 'COMPLETED',
  },
  {
    id: 'XFER-DEMO-002',
    evidenceId: 'EVD-DEMO-001',
    timestamp: '2026-08-03T11:15:00.000Z',
    fromLabel: 'Demo Evidence Vault',
    toLabel: 'Demo Review Desk',
    action: 'Transferred',
    notes: 'Fictional transfer prepared for internal verification review.',
    status: 'COMPLETED',
  },
  {
    id: 'XFER-DEMO-003',
    evidenceId: 'EVD-DEMO-001',
    timestamp: '2026-08-04T15:40:00.000Z',
    fromLabel: 'Demo Review Desk',
    toLabel: 'Demo Case Analyst',
    action: 'Reviewed',
    notes: 'Fictional review completed for archive compliance and documentation.',
    status: 'REVIEWED',
  },
  {
    id: 'XFER-DEMO-004',
    evidenceId: 'EVD-DEMO-004',
    timestamp: '2026-07-25T10:25:00.000Z',
    fromLabel: 'Demo Field Team',
    toLabel: 'Demo Evidence Locker B',
    action: 'Logged',
    notes: 'Fictional physical item entered into the controlled evidence log.',
    status: 'COMPLETED',
  },
  {
    id: 'XFER-DEMO-005',
    evidenceId: 'EVD-DEMO-004',
    timestamp: '2026-07-26T09:10:00.000Z',
    fromLabel: 'Demo Evidence Locker B',
    toLabel: 'Demo Secure Transfer Desk',
    action: 'Transferred',
    notes: 'Fictional transfer to secure handling desk pending review authorization.',
    status: 'PENDING',
  },
  {
    id: 'XFER-DEMO-006',
    evidenceId: 'EVD-DEMO-005',
    timestamp: '2026-07-29T18:30:00.000Z',
    fromLabel: 'Demo Observation Post 3',
    toLabel: 'Demo Evidence Vault',
    action: 'Received',
    notes: 'Fictional video capture received for validation scheduling.',
    status: 'COMPLETED',
  },
  {
    id: 'XFER-DEMO-007',
    evidenceId: 'EVD-DEMO-006',
    timestamp: '2026-08-11T12:05:00.000Z',
    fromLabel: 'Demo Secure Archive Cabinet',
    toLabel: 'Demo Review Panel',
    action: 'Reviewed',
    notes: 'Fictional restricted statement sheet reviewed under controlled access.',
    status: 'REVIEWED',
  },
]
